import 'dotenv/config';
import logger from './logger.js';

/**
 * Verify reCaptcha v3 token
 * @param {string} token - reCaptcha token from client
 * @param {string} action - Action name (e.g., 'register', 'login', 'contact')
 * @returns {Promise<{valid: boolean, score: number}>}
 * @throws {Error} If token is invalid or verification fails
 */
export async function verifyRecaptchaToken(token, action) {
  logger.debug(`[reCaptcha v3] Received token for verification. Type: ${typeof token}, Length: ${token ? token.length : 0}`);

  if (!token || typeof token !== 'string' || token.trim() === '') {
    const err = new Error('reCaptcha token is required and must be a non-empty string');
    err.status = 400;
    throw err;
  }

  const secretKey = process.env.RECAPTCHA_SECRET_KEY;

  if (!secretKey) {
    logger.error('RECAPTCHA_SECRET_KEY environment variable is not set');
    const err = new Error('reCaptcha configuration error');
    err.status = 500;
    throw err;
  }

  // Handle fallback tokens generated by the frontend when the script fails to load
  if (token.startsWith('fallback_token')) {
    logger.warn(`Received fallback reCaptcha token for action '${action}'. Allowing request to proceed with warning.`);
    return { valid: true, score: 0.5 };
  }

  const url = 'https://www.google.com/recaptcha/api/siteverify';
  const params = new URLSearchParams();
  params.append('secret', secretKey);
  params.append('response', token);

  logger.debug(`Verifying reCaptcha v3 token for action: ${action}`);

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: params.toString(),
  });

  if (!response.ok) {
    const errText = await response.text();
    logger.error(`reCaptcha API returned HTTP ${response.status}: ${errText}`);
    const err = new Error('Failed to communicate with Google reCaptcha services');
    err.status = 502;
    throw err;
  }

  const data = await response.json();
  logger.debug(`reCaptcha API response for action '${action}':`, JSON.stringify(data));

  if (!data.success) {
    const reason = data['error-codes'] ? data['error-codes'].join(', ') : 'Unknown reason';
    logger.warn(`reCaptcha verification failed: ${reason}`);
    return {
      valid: false,
      score: 0,
    };
  }

  if (action && data.action !== action) {
    logger.warn(`reCaptcha action mismatch. Expected: ${action}, Got: ${data.action}`);
    return {
      valid: false,
      score: 0,
    };
  }

  const score = data.score ?? 0;
  logger.info(`reCaptcha verification successful for action '${action}': score=${score}`);

  if (score < 0.5) {
    logger.warn(`reCaptcha score ${score} is below threshold 0.5 for action '${action}'`);
    return {
      valid: false,
      score: score,
    };
  }

  return {
    valid: true,
    score: score,
  };
}

/**
 * Verify reCaptcha v3 token (alias for verifyRecaptchaToken)
 * @param {string} token - reCaptcha token from client
 * @param {string} action - Action name (e.g., 'register', 'login')
 * @returns {Promise<{valid: boolean, score: number}>}
 * @throws {Error} If token is invalid or verification fails
 */
export async function verifyRecaptchaV3Token(token, action) {
  return verifyRecaptchaToken(token, action);
}